deck_writer_task:
  description: >
    Using the supplied title and presentation outline, create an 5 word title for both
    the introductory slide and the conclusion.
    For the introduction slide the title should be engaging and the presenter notes in a single sentence introduce the subject.
    A short paragraph describing for the agenda presenter notes
    The conclusion slide should have a concise title and subtitle with brief conclusing presenter notes.
    presentation along with presenter notes that are 40 words maximum.

    Here is the topic for the presentation: {topic}

    Here is the outline of the entire presentation:\n\n
    {presentation_outline}
  expected_output: >
    Title and supporting presenter notes for opening slide. Presenter notes summarising the talks content for the agenda.Title, subtitle and supporting presenter notes for the summary slide.
  agent: deck_writer