research_task:
  description: >
    Research the provided topic of {topic} to gather the most important information that will 
    be useful in creating a report outline. Ensure you focus on high-quality, reliable sources.

    Here is some additional information about the author's desired goal for the report:\n\n {goal}
  expected_output: >
    A set of key points and important information about {topic} that will be used to create the outline.
  agent: researcher

reporting_task:
  description: >
    Create a report outline with sections in sequential order based on the research findings. 
    Ensure that each section has a title and a brief description that highlights the topics and subtopics to be covered.
    It's important to note that each section is only going to be {section_length} words or less and should be limited to only {section_count} setions.
    Also, make sure that you do not duplicate any sections or topics in the outline.

    Here is some additional information about the author's desired goal for the report:\n\n {goal}

  expected_output: >
    An outline of sections, with titles and descriptions of what each section will contain.
  agent: reporting_analyst
